'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import AppHeader from '@/components/app.header';
import AppFooter from '@/components/app.footer';
import Container from 'react-bootstrap/Container';
import NavRight from '@/components/app.nav_right';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import useSWR, { mutate } from 'swr';
import { UserContext } from '@/context/UserContext';
import { SessionProvider } from 'next-auth/react';
import { useEffect, useState } from 'react';
import { checkApiStatus } from './globalfunction';




const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const provider = typeof window !== 'undefined' ? localStorage.getItem('provider') : null;
  const decodedEmail = typeof window !== 'undefined' ? localStorage.getItem('emailUser') : null;
  const [cards, setCards] = useState<ICart[]>([]);



  const fetcher = (url: string) => {
    return fetch(url, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${typeof window !== 'undefined' ? localStorage.getItem('authToken') : ''}`
      },
      credentials: 'include'
    })
      .then((res) => {
        if (res.status === 401) {
          checkApiStatus(401, true);

        }
        return res.json();
      });
  };


  const { data, error, isLoading } = useSWR(
    decodedEmail ? `http://localhost:8080/api/person/auth/getPerson?email=${decodedEmail}&accountFrom=${provider}` : null,
    fetcher,
    {
      revalidateIfStale: false,
      revalidateOnFocus: false,
      revalidateOnReconnect: false,
    }
  );

  const getCardsByPersonId = async (personId: number) => {
    const url = `http://localhost:8080/api/cart/auth/getCartByPersonId?personId=${personId}`
    try {
      const response = await fetch(url,
        {
          method: 'GET',
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${typeof window !== 'undefined' ? localStorage.getItem('authToken') : ''}`
          },
          credentials: 'include'
        });
      if (response.status === 401) {
        await checkApiStatus(401, false);
        await getCardsByPersonId(personId);
      }
      const listCart: [ICart, ICourse][] = await response.json()

      const dataCart: ICart[] = listCart.map(item => (
        {
          course: item[1],
          selected: false
        }
      ))

      setCards(dataCart)

    }
    catch (error) {
    }
  }



  useEffect(() => {
    if (data && data.personId) {
      getCardsByPersonId(data.personId);
    }
  }, [data]);



  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <UserContext.Provider value={{
            user: data, cards, updateCards: setCards
          }}>
            <AppHeader user={data} />
            {children}
            <AppFooter />
            <NavRight />
            <ToastContainer position="top-center" />
          </UserContext.Provider>
        </SessionProvider>
      </body>

    </html>
  )
}
