'use client'
import { Inter } from 'next/font/google'
import UserLayOut from '@/components/app.userlayout';
import { UserContext, useUser } from '@/context/UserContext';
import '@/styles/user.css'





const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const users = useUser();
  const user = users?.user;


  if (!user) {
    return (
        <div className="error-noUser">
          <img src="/img/working.png" alt="" />
          <span>You Need To Login For Using Service</span>
        </div>
    );
  }


  

  return (
    <UserLayOut>
            {children}
    </UserLayOut>


  )
}
